use Mix.Config

# Configure your database
# config :scandoc, Scandoc.Repo,
#   username: "postgres",
#   password: "postgres",
#   database: "scandoc_dev",
#   hostname: "localhost",
#   show_sensitive_data_on_connection_error: true,
#   pool_size: 10

database_url =
  System.get_env("DATABASE_URL") || "postgres://scandoc:EliScandoc68@localhost:5432/scandoc_dev"

config :scandoc, Scandoc.Repo,
  # ssl: true,
  url: database_url,
  migration_timestamps: [type: :utc_datetime_usec],
  migration_lock: nil,
  queue_target: 5000,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "30")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :scandoc, ScandocWeb.Endpoint,
  http: [port: 9090],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :scandoc, ScandocWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/scandoc_web/(live|views)/.*(ex)$",
      ~r"lib/scandoc_web/templates/.*(eex)$"
    ]
  ]

config :scandoc,
  full_upload_path: "/home/eli/projects/scandocs/priv/static/uploads",
  full_download_path: "/home/eli/projects/scandocs/priv/static/downloads"

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
